version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Hansaka123@
      POSTGRES_DB: studentdb
    ports:
      - "5433:5432"

  spring-boot-app:
    build: .
    ports:
      - "8089:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/studentdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Hansaka123@
